### ISSUE TITLE
Add missing event/observable information

### ISSUE THREAD

**Issue by justfalter** [cikl/cikl#104]
There is additional information available via the API that is not currently being displayed:
- Events:
  - [ ] feed_provider / feed_name
  - [ ] tags
  - [ ] Number of observables?
- Observables:
  - [ ] Observable type
  - dns_answer types:
    - [ ] ipv4 For DNS A records
    - [ ] ipv6 For DNS AAAA records

**Comment by justfalter** [comment]
@dsweet04 can you please update this ticket so we know where things are at?

**Comment by dsweet04** [comment]
This has all been added.
