### ISSUE TITLE
UI loses track of search term after clicking hyperlinked fqdn

### ISSUE THREAD

**Issue by justfalter** [cikl/cikl#109]
Steps to reproduce:
1. Select 'fqdn'
2. Type in 'google.com'
3. Scroll down and click on hyperlink for 'ns3.google.com'
4. (New page comes up with ns3.google.com results, and 'ns3.google.com' in the search field)
5. Click on search button
6. You are returned results as though you had searched for fqdn 'google.com', not 'ns3.google.com'.

Expectations:
- Click the search button would search for the type and term in the shown input fields.

**Comment by dsweet04** [comment]
This has been fixed and will be included in the next pull.

**Comment by dsweet04** [comment]
Closed by commit 7e8b079.
