### ISSUE TITLE
Win8 not able to complete vagrant/puppet script

### ISSUE THREAD

**Issue by nosteve** [cikl/cikl#25]
Latest vagrant/virtualbox installed, brings up vm but puppet script appears to hang. Here's output:

C:\Users\charlie\src\cikl>vagrant up
Bringing machine 'cikl' up with 'virtualbox' provider...
==> cikl: Checking if box 'ubuntu/trusty64' is up to date...
==> cikl: Clearing any previously set network interfaces...
==> cikl: Preparing network interfaces based on configuration...
    cikl: Adapter 1: nat
==> cikl: Forwarding ports...
    cikl: 22 => 2222 (adapter 1)
    cikl: 80 => 8080 (adapter 1)
==> cikl: Running 'pre-boot' VM customizations...
==> cikl: Booting VM...
==> cikl: Waiting for machine to boot. This may take a few minutes...
    cikl: SSH address: 127.0.0.1:2222
    cikl: SSH username: vagrant
    cikl: SSH auth method: private key
    cikl: Warning: Connection timeout. Retrying...
    cikl: Warning: Remote connection disconnect. Retrying...
    cikl: Warning: Remote connection disconnect. Retrying...
==> cikl: Machine booted and ready!
==> cikl: Checking for guest additions in VM...
==> cikl: Mounting shared folders...
    cikl: /vagrant => C:/Users/charlie/src/cikl
    cikl: /tmp/vagrant-puppet-2/manifests => C:/Users/charlie/src/cikl/puppet/ma
nifests
==> cikl: Running provisioner: puppet...
Running Puppet with default.pp...
stdin: is not a tty
Warning: Config file /etc/puppet/hiera.yaml not found, using Hiera defaults
Notice: Compiled catalog for vagrant-ubuntu-trusty-64.gateway.2wire.net in envir
onment production in 14.65 seconds
Notice: /Stage[init]/Fix_resolvconf/File_line[add single-request-reopen to resol
vconf]/ensure: created
Notice: /Stage[init]/Fix_resolvconf/Exec[refresh resolvconf]: Triggered 'refresh
' from 1 events
Notice: /Stage[main]/Cikl::Kibana::Install/File[/opt/kibana]/ensure: created
Notice: /Stage[main]/Cikl::Logstash::Install/File[disable-logstash-web]/ensure:
defined content as '{md5}3c78b35502b2693fefdfc51cba3a53a5'
Notice: /Stage[main]/Cikl::Nginx::Install/Package[nginx]/ensure: ensure changed
'purged' to 'present'
Notice: /Stage[main]/Cikl::Nginx::Install/File[/etc/nginx/sites-available/cikl.c
onf]/ensure: defined content as '{md5}1de01b401fd69ec3f00a4464ef696862'
Notice: /Stage[main]/Cikl::Nginx::Install/File[/etc/nginx/sites-enabled/default]
/ensure: removed
Notice: /Stage[main]/Perl/Package[perl-doc]/ensure: ensure changed 'purged' to '
present'
Notice: /Stage[main]/Staging/File[/opt/staging]/ensure: created
Notice: /Stage[main]/Cikl::Packages::Libxml2-dev/Cikl::Package[cikl::packages::l
ibxml2-dev]/Package[cikl::packages::libxml2-dev]/ensure: ensure changed 'purged'
 to 'present'
Notice: /Stage[main]/Cikl::Packages::Java7/Cikl::Package[cikl::packages::java7]/
Package[cikl::packages::java7]/ensure: ensure changed 'purged' to 'present'
Notice: /Stage[main]/Cikl::Packages::Build-essential/Cikl::Package[cikl::package
s::build-essential]/Package[cikl::packages::build-essential]/ensure: ensure chan
ged 'purged' to 'present'
Notice: /Stage[main]/Cikl::Packages::Libssl-dev/Cikl::Package[cikl::packages::li
bssl-dev]/Package[cikl::packages::libssl-dev]/ensure: ensure changed 'purged' to
 'present'
Notice: /Stage[main]/Elasticsearch::Repo/Apt::Source[elasticsearch]/Apt::Key[Add
 key: D88E42B4 from Apt::Source elasticsearch]/Exec[6b09b6a8542a1baa5f0a4c4d2527
f8108f8de821]/returns: executed successfully
Notice: /Stage[main]/Rabbitmq::Repo::Apt/Apt::Source[rabbitmq]/Apt::Key[Add key:
 056E8E56 from Apt::Source rabbitmq]/Exec[6e22ea6df620a8e44d17b8a5b025c3f32d362a
5c]/returns: executed successfully
Notice: /Stage[main]/Cikl::Kibana::Install/Staging::File[kibana-3.0.1.tar.gz]/Fi
le[/opt/staging/cikl]/ensure: created
Notice: /Stage[main]/Cikl::Kibana::Install/Staging::File[kibana-3.0.1.tar.gz]/Fi
le[/opt/staging/cikl/kibana-3.0.1.tar.gz]/ensure: defined content as '{md5}210e6
6901b22304a2bada3305955b115'
Notice: /Stage[main]/Rabbitmq::Repo::Apt/Apt::Source[rabbitmq]/File[rabbitmq.lis
t]/ensure: created
Notice: /Stage[main]/Elasticsearch::Repo/Apt::Source[elasticsearch]/File[elastic
search.list]/ensure: created
Notice: /Stage[main]/Logstash::Repo/Apt::Source[logstash]/File[logstash.list]/en
sure: created
Notice: /Stage[main]/Apt::Update/Exec[apt_update]: Triggered 'refresh' from 3 ev
ents
Notice: /Stage[main]/Rabbitmq::Install/Package[rabbitmq-server]/ensure: ensure c
hanged 'purged' to 'present'
Notice: /Stage[main]/Rabbitmq/Rabbitmq_plugin[rabbitmq_management]/ensure: creat
ed
Notice: /Stage[main]/Rabbitmq::Config/File[rabbitmq.config]/ensure: defined cont
ent as '{md5}ac149d64c99016a406d603112e380410'
Notice: /Stage[main]/Logstash::Package/Package[logstash]/ensure: ensure changed
'purged' to 'present'
Notice: /Stage[main]/Logstash::Config/File[/etc/logstash/patterns]/ensure: creat
ed
Notice: /Stage[main]/Cikl::Logstash::Install/File[elasticsearch-cikl-template]/e
nsure: defined content as '{md5}bdb4d35fa124cd5fce18d1cdf2d6c153'
Notice: /Stage[main]/Logstash::Config/File[/etc/logstash/plugins]/ensure: create
d
Notice: /Stage[main]/Logstash::Config/File[/etc/logstash/plugins/logstash]/ensur
e: created
Notice: /Stage[main]/Logstash::Config/File[/etc/logstash/plugins/logstash/filter
s]/ensure: created
Notice: /Stage[main]/Logstash::Config/File[/etc/logstash/plugins/logstash/codecs
]/ensure: created
Notice: /Stage[main]/Logstash::Config/File[/etc/logstash/plugins/logstash/inputs
]/ensure: created
Notice: /Stage[main]/Rabbitmq::Config/File[/etc/rabbitmq/ssl]/ensure: created
Notice: /Stage[main]/Logstash::Config/File[/etc/logstash/plugins/logstash/output
s]/ensure: created
Notice: /Stage[main]/Cikl::Nginx::Install/File[/etc/nginx/sites-enabled/cikl.con
f]/ensure: created
Notice: /Stage[main]/Cikl::Nginx::Install/Service[nginx]: Triggered 'refresh' fr
om 1 events
Notice: /Stage[main]/Logstash::Config/File_concat[ls-config]/ensure: created
Notice: /Stage[main]/Logstash::Service/Logstash::Service::Init[logstash]/Service
[logstash]/ensure: ensure changed 'stopped' to 'running'
Notice: /Stage[main]/Cikl::Kibana::Install/Staging::Extract[kibana-3.0.1.tar.gz]
/Exec[extract kibana-3.0.1.tar.gz]/returns: executed successfully
Notice: /Stage[main]/Cikl::Kibana::Install/File[/opt/kibana/current]/ensure: cre
ated
Notice: /Stage[main]/Cikl::Kibana::Install/File[/opt/kibana/current/config.js]/c
ontent: content changed '{md5}346ccb6b9105a62d6cef37a7ea17edc0' to '{md5}5f08226
9e74084d1f099dd51e59302f6'
Notice: /Stage[main]/Cikl::Kibana::Install/File[/opt/kibana/current/app/dashboar
ds/cikl.json]/ensure: defined content as '{md5}87e82b9c1cd93a10794ddb6f7eb7e664'

Notice: /Stage[main]/Rabbitmq::Config/File[rabbitmq-env.config]/ensure: defined
content as '{md5}24a999360296126ab92292e5b105d9cd'
## 

Seems to stay on this step and command prompt doesn't return. Connecting to localhost:8080 shows kibana but gives this error:

Upgrade Required Your version of Elasticsearch is too old. Kibana requires Elasticsearch 0.90.9 or above.

**Comment by nosteve** [comment]
Experiencing build issue on Win7, capturing here during troubleshooting in case relevant to build issue on Windows in general.

```
Notice: /Stage[main]/Logstash::Service/Logstash::Service::Init[logstash]/Service
[logstash]/ensure: ensure changed 'stopped' to 'running'
Notice: Finished catalog run in 1451.05 seconds


Stderr from the command:

stdin: is not a tty
Error: Command exceeded timeout
Error: /Stage[main]/Profile::Smrt/Exec[profile::smrt::install]/returns: change f
rom notrun to 0 failed: Command exceeded timeout
Warning: /Stage[main]/Profile::Smrt/Exec[profile::smrt::install_rabbitmq]: Skipp
ing because of failed dependencies
```

**Comment by justfalter** [comment]
It's taking a long time to install the perl modules. This is usually due to slow link-speeds to CPAN. Just re-run "vagrant provision" and it will pick up where it left off.

**Comment by justfalter** [comment]
Spoke with @nosteve last night, and everything is working now.
