### ISSUE TITLE
Revisit Cikl 'Event', and ensure that we are capturing everything we need in there.

### ISSUE THREAD

**Issue by justfalter** [cikl/cikl#26]
I'm not 100% sure that we're capturing everything we need within our current 'Event'. Likewise, there's probably stuff in there we don't need.

**Comment by justfalter** [comment]
Here's where I've defined the current 'event' model: https://github.com/cikl/p5-Cikl/blob/master/lib/Cikl/Models/Event.pm

**Comment by pierre427** [comment]
Suggestions to remove:

detecttime, reporttime fills the immediate purpose of knowing when it was injected to the DB, should be hidden option to set during import (backfilling DB with historical data)
Assessment and description, merge to description
Address should be branched out to IPv4, IPv6, URL, emailaddr and domainname (fqdn or domain) 
alternativeid never served a purpose IMO
malware_md5, malware_sha1, malware_sha256, malware_sha512 should stay; shorthand here (md5/sha1) should disappear or only use shorthand
Do we need portlist or can be included in the URL field and an additional field+index in that table?
Ditto for protocol
severity never seemed very useful or reliable; use the source (feed) for severity as it might change and easier to change in one place

I would also suggest creating a set of tables allowing for importing the paid maxmind geoip DB 141 (orgname + country) as well as the free maxmind IP2asn database located here http://dev.maxmind.com/geoip/legacy/geolite/

This will allow for a search via country, orgname, prefix, asn, as name and so on and allow for enriching the data accessed in these fields

**Comment by justfalter** [comment]
> Suggestions to remove:
> 
> detecttime, reporttime fills the immediate purpose of knowing when it was injected to the DB, should be hidden option to set during import (backfilling DB with historical data)

I'm not sure if you're actually suggesting we remove these fields or not. 
- **reporttime** is the timestamp for when the data was actually imported into the system
- **detecttime** is when the item being reported was initially detected. It's optional, and defaults to the reporttime. 

> Assessment and description, merge to description

The assessment identifies the type of data being reported (botnet, scanner, phisher, etc).
Here's an example feed for reference: https://github.com/cikl/cikl-feeds/blob/master/etc/alienvault.cfg ... If anything, I'd like to have a strict enumeration of the valid values for **assessment**, so that we can be sure we don't end up with a bunch of crud in there.

> Address should be branched out to IPv4, IPv6, URL, emailaddr and domainname (fqdn or domain) 

Already got it! https://github.com/cikl/p5-Cikl/tree/master/lib/Cikl/Models/Address
However, I think it would be a good idea to move this up to the top level, as opposed to putting it beneath 'address'. 

> alternativeid never served a purpose IMO

Definitely should be removed from the event model, yes. If you know what feed the data came from, you know this information, already.

> malware_md5, malware_sha1, malware_sha256, malware_sha512 should stay; shorthand here (md5/sha1) should disappear or only use shorthand

Agreed!

> Do we need portlist or can be included in the URL field and an additional field+index in that table?
> Ditto for protocol

It's definitely relevant in many cases (https://github.com/cikl/cikl-feeds/search?q=portlist&type=Code) ... These seem to be for network-layer services (tcp/22).. The fact that there are ranges of port numbers tells me that it wouldn't fit into a URL. I do think we should be keeping this. 

> severity never seemed very useful or reliable; use the source (feed) for severity as it might change and easier to change in one place

Agreed.

> I would also suggest creating a set of tables allowing for importing the paid maxmind geoip DB 141 (orgname + country) as well as the free maxmind IP2asn database located here http://dev.maxmind.com/geoip/legacy/geolite/
> 
> This will allow for a search via country, orgname, prefix, asn, as name and so on and allow for enriching the data accessed in these fields

This should probably go into a new issue.

**Comment by pierre427** [comment]
Agree with all of the feedback.

**Comment by justfalter** [comment]
Thanks, @pierre427 . I'll go ahead and make changes to the model.

**Comment by justfalter** [comment]
I'd like to move toward the industry standard terminology of "Observables" and "Observations" ... This should align us with where many security solutions are going. Any objections?

**Comment by pierre427** [comment]
Not from me, go for it

**Comment by justfalter** [comment]
I think we've done as much as we can, here.
