### ISSUE TITLE
Basic high-level dashboard for looking at results. 

### ISSUE THREAD

**Issue by justfalter** [cikl/cikl#27]

**Comment by nosteve** [comment]
User needs a summary overview of the results without digging into the details. At the top of the kibana view returned after performing a query, we need a window that uses large fonts to give the following information:
- First hit
  -- The first date/time Cikl has seen this value in the logs
- Last hit
  -- Same as above, last
- Diversity
  -- Number of feeds and percentage that contain a hit
  -- Ex. 5/25 feeds, 25% occurrence
  -- Big numbers, small labels/descriptions
  -- Also consider the word "Popularity" here
- Searches
  -- How many searches have occurred for this record ever
  -- How many searches in the last 30 days
- Average Severity
  -- Average severity level of hits, dependent on config of feeds
- Highest Confidence
  -- Highest confidence level across feeds reporting back

Others may be added, need to discuss further after initial implementation. Should be a panel with large fonts that attracts attention but visually consumable. Consider "building" animation that grows from zero when data is initially presented.

**Comment by pierre427** [comment]
Here's a sample from another system for comparison:

docs.google.com was found floating belly-up in the Phishtank domain list. ( First seen 2014-01-02 and most recently spotted today ) ( Internal Revenue Service::http://www.phishtank.com/phish_detail.php?phish_id=2450029 )
feedproxy.google.com was found in the Alexa Top 1 million domain list. ( First seen 2013-12-30 and most recently spotted yesterday ) ( Alexa #17010 )
sites.google.com was found floating belly-up in the Phishtank domain list. ( First seen 2013-12-31 and most recently spotted today ) ( Sulake Corporation::http://www.phishtank.com/phish_detail.php?phish_id=2247148 )
spreadsheets.google.com was found floating belly-up in the Phishtank domain list. ( Spotted 2014-04-30 ) ( Other::http://www.phishtank.com/phish_detail.php?phish_id=2360284 )
www.google.com was found floating belly-up in the Phishtank domain list. ( First seen 2013-12-31 and most recently spotted today ) ( Other::http://www.phishtank.com/phish_detail.php?phish_id=2373901 )

It might be efficient to use a word cloud model for this instead, with onmouseover to get a particular feed's details.

**Comment by dsweet04** [comment]
*******************\* Panels ********************
So based on the items we want to display, a new panel will be needed for almost everything despite how we format the data at the elasticsearch/logstash level. I think I may want to create a separate panel for each:
- First hit & Last hit
- Number of feeds & percentage
- Search history
- Severity count & percentages (current stats panel requires numeric values not low/medium/high)
- If we wanted to display the single highest confidence at the top it would be a panel. The highest confidence results could be easily displayed by sorting the table view of results. 

We could script our panel code getting dropped in during the setup https://github.com/elasticsearch/kibana/tree/master/src/app/panels

*******************\* Maps ********************
For Kibana mapping options there are two panels that do this. Both would require the fields being added in at the elasticsearch level. I think we should add both if it is easy enough.

First we could make a map that plots all items by geolocation: (bettermap panel)
Experimental // Displays geo points in clustered groups on a map. The caveat for this panel is that, for better or worse, it does NOT use the terms facet and it does query sequentially. This however means that it transfers more data and is generally heavier to compute, while showing less actual data. If you have a time filter, it will attempt to show to most recent points in your search, up to your defined limit

Second there is a panel that plots all items by 2 letter country code: (map panel)
Stable // Displays a map of shaded regions using a field containing a 2 letter country , or US state, code. Regions with more hit are shaded darker. Node that this does use the elasticsearch terms facet, so it is important that you set it to the correct field.

**Comment by dsweet04** [comment]
This issues was merged and clarified in issue #77
