### ISSUE TITLE
Vagrant needs an initial data-set or import of data

### ISSUE THREAD

**Issue by justfalter** [cikl/cikl#28]
Maybe just an hourly run, but run immediately. Do we want it to be run automatically upon provisioning, or just have it as an instruction step?

**Comment by pierre427** [comment]
Last step during install: Do you want to do any post deployment configuration, or run the first jobs now?

**Comment by nosteve** [comment]
This will only be for devs and can be manual, cmdline, whatever. A baseline set of predictable data to make it easier on the UI devs.

**Comment by nosteve** [comment]
The kibana 10 minute walkthrough shows an example of initial import of a json file in "elasticsearch bulk import" format. They import it using:

curl -XPUT localhost:9200/_bulk --data-binary @shakespeare.json

http://www.elasticsearch.org/guide/en/kibana/current/using-kibana-for-the-first-time.html

**Comment by justfalter** [comment]
@nosteve That's awesome!

In the short term, I'm going to update the README to include details on how to run cikl_smrt to import data.

**Comment by justfalter** [comment]
Alright, I've updated the readme with instructions on how to run cikl_smrt. See b1cc4a29c33e152e9ef52204db9436a8d409bbef

**Comment by justfalter** [comment]
Alrighty, who is going to be doing the actual work of creating a basic data set?
