### ISSUE TITLE
Queries based on ipv4, ipv4 range/cidr, fqdn, email, url, and ASN

### ISSUE THREAD

**Issue by justfalter** [cikl/cikl#30]
We need to make sure we can do this.

**Comment by pierre427** [comment]
Also based on shared NS, shared MX, orgname wildcard, SOA, AS name wildcard, registration plaintext search (for whois of IP or domain)

**Comment by justfalter** [comment]
Breaking these out.

**Comment by justfalter** [comment]
Broken out into: #116 #115 #114 #113 #31 #34 #32 #33
