### ISSUE TITLE
Queries return related records

### ISSUE THREAD

**Issue by nosteve** [cikl/cikl#60]
Cikl should return all records related to the input in addition to records that specifically match. For instance, an IP address query should return all hostname records that resolved to the IP address during the time window queried, all records related to the IP address' associated ASN. Other relationships may be possible and should be considered.

A stretch goal is to use a "collapseable" widget to organize and present this data visually, with each record type called out under its own section.

**Comment by nosteve** [comment]
More detailed requirements including some direction on how queries are performed and how data is stored and displayed.

User will input a query value and choose the type from the following list:
- IP Address
- IP Network (CIDR)
- DNS
  -- I see this as being partial or full domain name, ex. server.domainname.com or domainname.com
- AS Number
- Consider MD5 and SHA1 - need to discuss how those relationships work, CIF does implement this in some fashion

Results returned are observables in one of two categories, Direct and Resolved. Direct observables can be intrinsically linked to a query. For example, an IP Address's relationship to IP Networks. Resolved observables require a lookup in order to link to other observables, for instance the relationship between an IP Address and a Hostname, or an ASN. Resolved records are created by a Resolver, which runs on Direct records on an interval (or immediately upon insertion) and inserts Resolved records along with a timestamp.

UI will show observables by the categories above using collapseable widget. Top observable category matches the type chosen by the user at query time and will be open (not collapsed) initially. Other categories that contain matches are collapsed and listed below. 
- I'm not married to the collapseable concept, consider normal headers and see how it looks. If not collapseable consider anchors to quickly navigate to the different data types.

User can click on the referenced value in observables, which will issue a new query for that value and show the new results. All values should be clickable and generate a new query in this fashion.

Returned for IP Address:
- Direct IP Address observables that contain that IP Address (top)
- Direct IP Network observables that include IP Address
- Resolved DNS records that resolve to IP Address
- Resolved ASN records that include IP Address

Returned for IP Network:
- Direct IP Address observables that include IP Network
- Resolved ASN records that include IP Network

Returned for DNS Name:
- Direct DNS observables that match DNS Name exactly
- Direct DNS observables that have the domain in common, recursive down to tld
  -- Consider dual suffix like .co.uk, might need tld list
- Resolved IP Address observables that resolve to DNS Name

Returned for ASN:
- Resolved IP Address observables that are contained in ASN
- Resolved IP Network observables that are contained in ASN

**Comment by justfalter** [comment]
> More detailed requirements including some direction on how queries are performed and how data is stored and displayed.
> 
> User will input a query value and choose the type from the following list:
> 
> IP Address
> IP Network (CIDR)
> DNS -- I see this as being partial or full domain name, ex. server.domainname.com or domainname.com
> AS Number
> 
> Consider MD5 and SHA1 - need to discuss how those relationships work, CIF does implement this in some fashion

I find all of these agreeable.

> Results returned are observables in one of two categories, Direct and Resolved. Direct observables can be intrinsically linked to a query. For example, an IP Address's relationship to IP Networks. Resolved observables require a lookup in order to link to other observables, for instance the relationship between an IP Address and a Hostname, or an ASN. Resolved records are created by a Resolver, which runs on Direct records on an interval (or immediately upon insertion) and inserts Resolved records along with a timestamp.

Perhaps it would be easier to think of it not in terms of who did the work or how something had been observed, but rather what types of data should be returned. The product of a DNS "A" query is a "dns_answer". Whether it was resolved by cikl-worker or was observed via pDNS, we still have a DNS 'A' record that consists of a FQDN and IPV4 address. 

> UI will show observables by the categories above using collapseable widget. Top observable category matches the type chosen by the user at query time and will be open (not collapsed) initially. Other categories that contain matches are collapsed and listed below.
> 
> I'm not married to the collapseable concept, consider normal headers and see how it looks. If not collapseable consider anchors to quickly navigate to the different data types.

It's not clear to me what is shown in the collapsible widget. Are you saying that:, for example, if a query for an IPv4 matches hundreds of DNS 'A' records, you'd like to see the top 10 most common FQDNs contained with those answers? 

> User can click on the referenced value in observables, which will issue a new query for that value and show the new results. All values should be clickable and generate a new query in this fashion.

This seems simple enough to me.  Question, though: is it valuable to offer two options one could take with an observable:
- **Starting a new query**: Navigate away from your existing query (like you said), forgetting about your previous one. 
- **Filtering existing query**: Basically _AND_ng your existing query based on the observable.
  - Started with "IPv4 1.2.3.4", and now searching for "IPV4 1.2.3.4" AND "FQDN foobar.com"
- **Expanding existing query**: Pretty much _OR_'ng the existing query*: 
  - Started with "IPV4 1.2.3.4", and now searching for "IPV4 1.2.3.4" OR "FQDN foobar.com" 

> Returned for IP Address:
> 
> Direct IP Address observables that contain that IP Address (top)
> Direct IP Network observables that include IP Address
> Resolved DNS records that resolve to IP Address
> Resolved ASN records that include IP Address
> Returned for IP Network:
> 
> Direct IP Address observables that include IP Network
> Resolved ASN records that include IP Network
> Returned for DNS Name:
> 
> Direct DNS observables that match DNS Name exactly
> Direct DNS observables that have the domain in common, recursive down to tld -- Consider dual suffix like .co.uk, might need tld list
> Resolved IP Address observables that resolve to DNS Name
> Returned for ASN:
> 
> Resolved IP Address observables that are contained in ASN
> Resolved IP Network observables that are contained in ASN

**Comment by nosteve** [comment]
> Perhaps it would be easier to think of it not in terms of who did the work or how something had been observed, but rather what types of data should be returned. The product of a DNS "A" query is a "dns_answer". Whether it was resolved by cikl-worker or was observed via pDNS, we still have a DNS 'A' record that consists of a FQDN and IPV4 address.

From our meeting in Chicago, I think we have a good strategy for this:
- Events can contain more than one observable to show relationships
- Direct / Resolved concept in data model, denoted in some fashion (color maybe) in UI

> It's not clear to me what is shown in the collapsible widget. Are you saying that:, for example, if a query for an IPv4 matches hundreds of DNS 'A' records, you'd like to see the top 10 most common FQDNs contained with those answers?

From the meeting: decided to do a timeline based view, denoting Direct vs Resolved in the UI using an effect such as color. Collapsible widget could be used to break up timeline, will keep in mind as we move forward.

> This seems simple enough to me. Question, though: is it valuable to offer two options one could take with an observable: 
> Starting a new query: Navigate away from your existing query (like you said), forgetting about your previous one.
> Filtering existing query: Basically _AND_ng your existing query based on the observable.
> Started with "IPv4 1.2.3.4", and now searching for "IPV4 1.2.3.4" AND "FQDN foobar.com"
> Expanding existing query: Pretty much OR'ng the existing query*:
> Started with "IPV4 1.2.3.4", and now searching for "IPV4 1.2.3.4" OR "FQDN foobar.com"

Don't want to add onto the current query, I feel this would be odd and confusing to the user have an unnatural feel from a browsing perspective. Could consider a "recent" tracker to allow for going back, but otherwise the previous query should be included in the new record so it would be easy to go back. 

For example 1.2.3.4 -> badhost.com would show a page that included 1.2.3.4 due to the relationship, clicking that link would take you back. Need to ensure back button works correctly as well.

Next step is to make something that looks like Mike's use case doc that defines how things are returned.

**Comment by nosteve** [comment]
Target Matching Requirements documented here: https://github.com/cikl/cikl/wiki/Target-Matching-Requirements

**Comment by justfalter** [comment]
Thanks @nosteve ! That looks good. 
I think it should be expanded to include e-mail and URLs, no?

**Comment by nosteve** [comment]
I can expand to include URLs. For emails, what would be the relationships? DNS has the admin email but that's more relevant for the fqdn probably. Phishing lists could apply and simply share relationship with fqdn. I'll write that up but welcome other ideas.

**Comment by justfalter** [comment]
Closing this after having broken this out into several tickets:
#116 #115 #114 #113 #31 #34 #32 #33
