### ISSUE TITLE
{DOC} Just the basics

### ISSUE THREAD

**Issue by coolacid** [cikl/cikl#61]
As Discussed with @justfalter 

There are people out there (especially me) that already have ELK stacks and would love to pipe the data directly into Elasticsearch and get it out of Kibana. 

Documentation around doing just that should probably be added sooner rather then later to support this function.

**Comment by justfalter** [comment]
@coolacid We've found that a simple ELK stack was unable to provide what the Cikl project truly needs. We've since dropped Kibana, and are developing a UI of our own. In the not-too-distant future we will be removing Logstash as a transport medium for our events.
