### ISSUE TITLE
Identify taxonomy/categories/attributes for events/observables

### ISSUE THREAD

**Issue by pierre427** [cikl/cikl#63]
http://www.lockheedmartin.ca/us/what-we-do/information-technology/cyber-security/cyber-kill-chain.html

We should look at mapping events into a major category by Kill Chain, see the link above.

**Comment by justfalter** [comment]
Here are some examples of things that we should be able to track/query:
- Hosts that scan for SSH servers
  - label of 'scanning'
  - Source IP
  - IP protocol (tcp/udp)
  - network service (SSH)
  - port number/range
- C2 server
  - label of 'c2' 
  - label of 'c2-server' (or something like this?)
  - Addressing for C2 server (host/proto/network service/port/url)
- C2 member
  - label of 'c2' 
  - label of 'c2-server' (or something like this?)
  - Addressing
- URLs that are hosting malware
  - URL for location of hosted malware
  - hashes for hosted malware (md5/sha1/etc)
  - **Question:** Type of malware?
  - Common name? 

What other things can you guys think of?
