### ISSUE TITLE
API results for UI Search

### ISSUE THREAD

**Issue by dsweet04** [cikl/cikl#74]
For the UI we currently have the following summary items listed:
- Date search artifact was first seen. This is the first detected date when available.
- Date search artifact was last seen. This is the last detected date when available.
- Percentage of feeds artifact was detected in. This is the number of unique feeds the artifact was detected in divided by the total number of feeds.
- Number of times identical artifacts were searched for.

**Comment by dsweet04** [comment]
Results Display

When displaying search results only the sources and the number of results from each source will be shown immediately following submit. Each of these source headers will be clickable to accordion out for all result details to be displayed. This seems like the most logical way to display results in a usable and digestible format. For this to work the following functionalities will be need from the API:
- Initial searches should return a list containing all sources with hits for the search term and the number of hits for each source.
- Searches by source and search term combination should be possible returning full event details.
- Pagination should be integrated with the search by source results. This will allow for displaying a set number of results at a time for the source and search term combination being viewed. (each accordion header)

**Comment by justfalter** [comment]
So, I've got to:
- [x] Allow specification of the size of the page (via 'size' parameter)
- [x] Allow specification of the offset of the events (via the 'from' parameter)
- [ ] add a field for the total results of the query, not just the size of the page. 
- [ ] Facet on the 'source' field for each event, and the number of occurrences of that source across all hits.
- [ ] Add ability to query by the 'source' field
- [ ] Add ability to sort by reporttime, detecttime

**Comment by dsweet04** [comment]
All that is correct and add facet for number of hits for each source

**Comment by dsweet04** [comment]
Oh and also:
- Add ability to sort alphabetically by source
- Add ability to sort alphabetically by fqdn
- Add ability to sort by IP address

**Comment by justfalter** [comment]
I don't think we can support sorting by fqdn and IP... There may be multiple IPs and fqdns per event.

**Comment by dsweet04** [comment]
This issues was merged and clarified in issue #77
